# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      
      - name: S3 Deploy
        # You may pin to the exact commit or the version.
        # uses: Reggionick/s3-deploy@aa30e453a8a4170856aac178f018c506a80501cf
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          # Directory to deploy
          folder: src
          # Name of AWS Bucket
          bucket: ${{ secrets.S3_BUCKET }}
          # The destination bucket region
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          # AWS CloudFront distribution ID
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} # optional
          # AWS CloudFront invalidation path(s)
          invalidation: '/*' # optional - '/' is default
          # Removes files in S3 that are not available in the local copy of the directory
          delete-removed: true # optional
          # Use this parameter to specify Cache-Control: no-cache, no-store, must-revalidate header
          # no-cache: # optional
          # Upload files with private ACL, needed for S3 static website hosting
          private: true # optional
